from __future__ import annotations

import importlib
import json
import pathlib
import sys
import unittest
from typing import Any, get_type_hints


REPO_ROOT = pathlib.Path(__file__).resolve().parents[1]


class SharedModuleBoundaryTest(unittest.TestCase):
    def test_flat_pigean_modules_are_compatibility_shims_for_package_modules(self) -> None:
        seam_expectations = (
            ("pigean.pipeline", "pigean_pipeline", "run_main_non_huge_pipeline"),
            ("pigean.dispatch", "pigean_dispatch", "run_main_pipeline"),
            ("pigean.gibbs", "pigean_gibbs", "run_outer_gibbs"),
            ("pigean.outputs", "pigean_outputs", "write_main_outputs_and_optional_phewas"),
            ("pigean.huge", "pigean_huge", "read_huge_statistics_bundle"),
            ("pigean.phewas", "pigean_phewas", "run_advanced_set_b_output_phewas_if_requested"),
        )
        src_root = str(REPO_ROOT / "src")
        if src_root not in sys.path:
            sys.path.insert(0, src_root)
        for package_module_name, flat_module_name, symbol_name in seam_expectations:
            with self.subTest(module=package_module_name, symbol=symbol_name):
                package_module = importlib.import_module(package_module_name)
                flat_module = importlib.import_module(flat_module_name)
                self.assertIs(getattr(package_module, symbol_name), getattr(flat_module, symbol_name))
                self.assertEqual(getattr(package_module, symbol_name).__module__, package_module_name)

    def test_pigean_package_app_owns_main_dispatch(self) -> None:
        app_source = (REPO_ROOT / "src" / "pigean" / "app.py").read_text(encoding="utf-8")
        support_source = (REPO_ROOT / "src" / "pigean" / "main_support.py").read_text(encoding="utf-8")
        package_init_source = (REPO_ROOT / "src" / "pigean" / "__init__.py").read_text(encoding="utf-8")
        package_main_source = (REPO_ROOT / "src" / "pigean" / "__main__.py").read_text(encoding="utf-8")
        self.assertFalse((REPO_ROOT / "src" / "pigean_legacy_main.py").exists())
        self.assertFalse((REPO_ROOT / "src" / "pigean" / "legacy_main.py").exists())
        self.assertIn("from . import main_support as pigean_main_support", app_source)
        self.assertIn("from . import dispatch as pigean_dispatch", app_source)
        self.assertIn("def run_main_pipeline(options, mode, services=None):", app_source)
        self.assertIn("services = pigean_main_support.build_cli_services()", app_source)
        self.assertIn("return pigean_dispatch.run_main_pipeline(options, mode, services=services)", app_source)
        self.assertIn("class PigeanMainServices:", support_source)
        self.assertIn("def build_cli_services() -> PigeanMainServices:", support_source)
        self.assertNotIn("def build_legacy_services(", support_source)
        self.assertNotIn("load_legacy_core", support_source)
        self.assertIn("from . import main", package_main_source)
        self.assertNotIn("from .legacy_main import main", package_main_source)
        self.assertIn('"main": ("app", "main")', package_init_source)
        self.assertIn('"app"', package_init_source)
        self.assertIn('"main_support"', package_init_source)
        self.assertNotIn('"legacy_main"', package_init_source)
        self.assertIn("def _build_prefilter_keep_mask(*args, **kwargs):", app_source)
        self.assertIn("return pigean_x_inputs_core.build_prefilter_keep_mask(", app_source)

    def test_pigean_dispatch_and_stage_modules_use_explicit_services_not_domain(self) -> None:
        dispatch_source = (REPO_ROOT / "src" / "pigean" / "dispatch.py").read_text(encoding="utf-8")
        pipeline_source = (REPO_ROOT / "src" / "pigean" / "pipeline.py").read_text(encoding="utf-8")
        outputs_source = (REPO_ROOT / "src" / "pigean" / "outputs.py").read_text(encoding="utf-8")
        phewas_source = (REPO_ROOT / "src" / "pigean" / "phewas.py").read_text(encoding="utf-8")
        self.assertIn("def run_main_pipeline(options, mode, services=None):", dispatch_source)
        self.assertNotIn("def run_main_pipeline(domain, options, mode):", dispatch_source)
        self.assertNotIn("domain.", dispatch_source)
        self.assertIn("services.log(", dispatch_source)
        self.assertIn("pigean_main_support.build_runtime_state(options)", dispatch_source)
        self.assertIn("pigean_main_support.build_mode_state(", dispatch_source)
        self.assertIn("pigean_main_support.configure_hyperparameters_for_main(", dispatch_source)
        self.assertIn("pigean_main_support.load_main_y_inputs(", dispatch_source)
        self.assertNotIn("domain.", pipeline_source)
        self.assertIn("pigean_main_support.build_inner_beta_sampler_common_kwargs(options)", pipeline_source)
        self.assertIn("pigean_main_support.run_main_adaptive_read_x(", pipeline_source)
        self.assertIn("pigean_main_support.set_const_Y(", pipeline_source)
        self.assertNotIn("domain.", outputs_source)
        self.assertIn("pigean_main_support.write_bundle_from_specs(", outputs_source)
        self.assertNotIn("domain.", phewas_source)
        self.assertIn("pigean_main_support.resolve_gene_phewas_input_decision_for_stage(", phewas_source)

    def test_pigean_runtime_helpers_live_in_package_runtime_module(self) -> None:
        runtime_source = (REPO_ROOT / "src" / "pigean" / "runtime.py").read_text(encoding="utf-8")
        state_source = (REPO_ROOT / "src" / "pigean" / "state.py").read_text(encoding="utf-8")
        support_source = (REPO_ROOT / "src" / "pigean" / "main_support.py").read_text(encoding="utf-8")
        package_init_source = (REPO_ROOT / "src" / "pigean" / "__init__.py").read_text(encoding="utf-8")
        self.assertFalse((REPO_ROOT / "src" / "pigean_legacy_main.py").exists())
        self.assertIn("def build_runtime_state(state_cls, options):", runtime_source)
        self.assertIn("def configure_hyperparameters_for_main(", runtime_source)
        self.assertIn("def temporary_state_fields(state, overrides, restore_fields):", runtime_source)
        self.assertIn("def bind_legacy_namespace(legacy_module=None):", state_source)
        self.assertIn("class PigeanState(object):", state_source)
        self.assertIn("from . import state as pigean_state", support_source)
        self.assertIn("pigean_state.bind_legacy_namespace(sys.modules[__name__])", support_source)
        self.assertIn("return pigean_runtime.build_runtime_state(pigean_state.PigeanState, options)", support_source)
        self.assertIn('"state"', package_init_source)
        self.assertIn("_configure_hyperparameters_for_main = functools.partial(", state_source)
        self.assertIn("pigean_runtime.configure_hyperparameters_for_main", state_source)
        self.assertIn("from . import main_support as pigean_main_support", state_source)

    def test_pigean_y_input_contract_and_dispatch_live_in_package_module(self) -> None:
        y_source = (REPO_ROOT / "src" / "pigean" / "y_inputs.py").read_text(encoding="utf-8")
        y_core_source = (REPO_ROOT / "src" / "pigean" / "y_inputs_core.py").read_text(encoding="utf-8")
        state_source = (REPO_ROOT / "src" / "pigean" / "state.py").read_text(encoding="utf-8")
        support_source = (REPO_ROOT / "src" / "pigean" / "main_support.py").read_text(encoding="utf-8")
        self.assertFalse((REPO_ROOT / "src" / "pigean_legacy_main.py").exists())
        self.assertIn("class YPrimaryInputsContract:", y_source)
        self.assertIn("class YReadContract:", y_source)
        self.assertIn("def build_main_y_read_contract(options):", y_source)
        self.assertIn("def load_main_y_inputs(", y_source)
        self.assertIn("def init_gene_locs(", y_core_source)
        self.assertIn("def read_gene_map(", y_core_source)
        self.assertIn("def apply_gene_covariates_and_correct_huge(", y_core_source)
        self.assertIn("def prepare_gene_covariate_regression_state(", y_core_source)
        self.assertIn("def maybe_append_input_gene_covariates(", y_core_source)
        self.assertIn("def read_y_pipeline(", y_core_source)
        self.assertIn("def set_const_Y(", y_core_source)
        self.assertIn("def read_primary_y_source(", y_core_source)
        self.assertIn("def materialize_y_on_gene_universe(", y_core_source)
        self.assertIn("YPrimaryInputsContract = pigean_y_inputs.YPrimaryInputsContract", support_source)
        self.assertIn("_read_Y = functools.partial(", state_source)
        self.assertIn("_set_const_Y = pigean_y_inputs_core.set_const_Y", support_source)
        self.assertIn("pigean_y_inputs_core.read_gene_map", state_source)
        self.assertIn("pigean_y_inputs_core.init_gene_locs", state_source)
        self.assertIn("pigean_y_inputs_core.apply_gene_covariates_and_correct_huge", state_source)
        self.assertIn("pigean_y_inputs_core.read_y_pipeline", state_source)
        self.assertIn("return pigean_y_inputs.load_main_y_inputs(", support_source)

    def test_pigean_x_input_orchestration_lives_in_package_module(self) -> None:
        x_source = (REPO_ROOT / "src" / "pigean" / "x_inputs.py").read_text(encoding="utf-8")
        x_core_source = (REPO_ROOT / "src" / "pigean" / "x_inputs_core.py").read_text(encoding="utf-8")
        support_source = (REPO_ROOT / "src" / "pigean" / "main_support.py").read_text(encoding="utf-8")
        self.assertFalse((REPO_ROOT / "src" / "pigean_legacy_main.py").exists())
        self.assertIn("def run_main_adaptive_read_x(", x_source)
        self.assertIn("def run_read_x_stage(", x_source)
        self.assertIn("def read_x_pipeline(", x_source)
        self.assertIn("def process_x_input_file(", x_core_source)
        self.assertIn("def maybe_prefilter_x_block(", x_core_source)
        self.assertIn("def ensure_gene_universe_for_x(", x_core_source)
        self.assertIn("return pigean_x_inputs.run_main_adaptive_read_x(", support_source)
        self.assertIn("return pigean_x_inputs.run_read_x_stage(", support_source)
        self.assertIn("return pigean_x_inputs.read_x_pipeline(", support_source)
        self.assertIn("_process_x_input_file = functools.partial(", support_source)
        self.assertIn("pigean_x_inputs_core.process_x_input_file", support_source)

    def test_pigean_gibbs_orchestration_lives_in_package_module(self) -> None:
        gibbs_source = (REPO_ROOT / "src" / "pigean" / "gibbs.py").read_text(encoding="utf-8")
        callback_source = (REPO_ROOT / "src" / "pigean" / "gibbs_callbacks.py").read_text(encoding="utf-8")
        state_source = (REPO_ROOT / "src" / "pigean" / "state.py").read_text(encoding="utf-8")
        shim_source = (REPO_ROOT / "src" / "pigean_gibbs.py").read_text(encoding="utf-8")
        self.assertFalse((REPO_ROOT / "src" / "pigean_legacy_main.py").exists())
        self.assertIn("class GibbsOrchestrationCallbacks:", gibbs_source)
        self.assertIn("def run_outer_gibbs(", gibbs_source)
        self.assertIn("def build_gibbs_callbacks(", callback_source)
        self.assertIn("from pigean import gibbs_callbacks as pigean_gibbs_callbacks", state_source)
        self.assertIn("callbacks = pigean_gibbs_callbacks.build_gibbs_callbacks(", state_source)
        self.assertIn("return pigean_gibbs.run_outer_gibbs(", state_source)
        self.assertIn("from pigean.gibbs import *", shim_source)

    def test_pigean_beta_and_prior_math_live_in_package_model_module(self) -> None:
        model_source = (REPO_ROOT / "src" / "pigean" / "model.py").read_text(encoding="utf-8")
        state_source = (REPO_ROOT / "src" / "pigean" / "state.py").read_text(encoding="utf-8")
        self.assertFalse((REPO_ROOT / "src" / "pigean_legacy_main.py").exists())
        self.assertIn("def build_inner_beta_sampler_common_kwargs(", model_source)
        self.assertIn("def calc_priors_from_betas(", model_source)
        self.assertIn("def finalize_gibbs_priors_for_sampling(", model_source)
        self.assertIn("def compute_gibbs_uncorrected_betas_and_defaults(", model_source)
        self.assertIn("def build_non_inf_beta_sampler_kwargs(", model_source)
        self.assertIn("def compute_gibbs_iteration_priors_from_betas(", model_source)
        self.assertIn("def calculate_gene_set_statistics(", model_source)
        self.assertIn("def calculate_non_inf_betas(", model_source)
        self.assertIn("def calculate_priors(", model_source)
        self.assertIn("_build_inner_beta_sampler_common_kwargs = pigean_model.build_inner_beta_sampler_common_kwargs", state_source)
        self.assertIn("pigean_model.finalize_gibbs_priors_for_sampling(", state_source)
        self.assertIn("pigean_model.compute_gibbs_uncorrected_betas_and_defaults(", state_source)
        self.assertIn("pigean_model.build_non_inf_beta_sampler_kwargs(", state_source)
        self.assertIn("pigean_model.compute_gibbs_iteration_priors_from_betas(", state_source)
        self.assertIn("return pigean_model.calculate_gene_set_statistics(", state_source)
        self.assertIn("return pigean_model.calculate_non_inf_betas(", state_source)
        self.assertIn("return pigean_model.calculate_priors(", state_source)

    def test_pigean_cli_uses_narrow_cli_helper_module(self) -> None:
        cli_source = (REPO_ROOT / "src" / "pigean" / "cli.py").read_text(encoding="utf-8")
        self.assertIn("from pegs_shared.cli import", cli_source)
        self.assertNotIn("from .pegs_utils import", cli_source)
        self.assertNotIn("from pegs_utils import", cli_source)

    def test_flat_pigean_cli_module_is_a_package_shim(self) -> None:
        cli_source = (REPO_ROOT / "src" / "pigean_cli.py").read_text(encoding="utf-8")
        self.assertIn("from pigean.cli import *", cli_source)

    def test_eaggl_cli_uses_narrow_cli_helper_module(self) -> None:
        cli_source = (REPO_ROOT / "src" / "eaggl" / "cli.py").read_text(encoding="utf-8")
        self.assertIn("from pegs_shared.cli import", cli_source)
        self.assertNotIn("from .pegs_utils import", cli_source)
        self.assertNotIn("from pegs_utils import", cli_source)

    def test_package_runtime_modules_use_pegs_shared_module_namespaces(self) -> None:
        pigean_source = (REPO_ROOT / "src" / "pigean" / "main_support.py").read_text(encoding="utf-8")
        eaggl_source = (REPO_ROOT / "src" / "eaggl" / "legacy_main.py").read_text(encoding="utf-8")
        self.assertIn("import pegs_shared.types as pegs_types", pigean_source)
        self.assertIn("import pegs_shared.gene_io as pegs_gene_io", pigean_source)
        self.assertIn("import pegs_shared.huge_cache as pegs_huge_cache", pigean_source)
        self.assertIn("import pegs_shared.xdata as pegs_xdata", pigean_source)
        self.assertIn("import pegs_shared.ydata as pegs_ydata", pigean_source)
        self.assertIn("import pegs_shared.bundle as pegs_bundle", pigean_source)
        self.assertIn("import pegs_shared.phewas as pegs_phewas", pigean_source)
        self.assertIn("import pegs_shared.regression as pegs_regression", pigean_source)
        self.assertIn("import pegs_shared.runtime_matrix as pegs_runtime_matrix", pigean_source)
        self.assertIn("import pegs_shared.types as pegs_types", eaggl_source)
        self.assertIn("import pegs_shared.cli as pegs_cli", eaggl_source)
        self.assertIn("import pegs_shared.gene_io as pegs_gene_io", eaggl_source)
        self.assertIn("import pegs_shared.xdata as pegs_xdata", eaggl_source)
        self.assertIn("import pegs_shared.ydata as pegs_ydata", eaggl_source)
        self.assertIn("import pegs_shared.bundle as pegs_bundle", eaggl_source)
        self.assertIn("import pegs_shared.phewas as pegs_phewas", eaggl_source)
        self.assertIn("import pegs_shared.regression as pegs_regression", eaggl_source)
        self.assertIn("import pegs_shared.runtime_matrix as pegs_runtime_matrix", eaggl_source)
        self.assertIn("import pegs_utils as pegs_utils_mod", eaggl_source)
        self.assertNotIn("from pegs_shared.types import", pigean_source)
        self.assertNotIn("from pegs_shared.cli import", pigean_source)
        self.assertNotIn("from pegs_shared.gene_io import", pigean_source)
        self.assertNotIn("from pegs_shared.bundle import", pigean_source)
        self.assertNotIn("from pegs_shared.phewas import", pigean_source)
        self.assertNotIn("from pegs_shared.types import", eaggl_source)
        self.assertNotIn("from pegs_shared.cli import", eaggl_source)
        self.assertNotIn("from pegs_shared.gene_io import", eaggl_source)
        self.assertNotIn("from pegs_shared.bundle import", eaggl_source)
        self.assertNotIn("from pegs_shared.phewas import", eaggl_source)
        self.assertNotIn("from pegs_utils import", eaggl_source)
        self.assertIn("pegs_compute_banded_y_corr_cholesky = pegs_runtime_matrix.compute_banded_y_corr_cholesky", pigean_source)
        self.assertIn("pegs_compute_banded_y_corr_cholesky = pegs_runtime_matrix.compute_banded_y_corr_cholesky", eaggl_source)

    def test_pegs_shared_gene_io_and_huge_cache_own_extracted_helpers(self) -> None:
        gene_io_source = (REPO_ROOT / "src" / "pegs_shared" / "gene_io.py").read_text(encoding="utf-8")
        huge_cache_source = (REPO_ROOT / "src" / "pegs_shared" / "huge_cache.py").read_text(encoding="utf-8")
        phewas_source = (REPO_ROOT / "src" / "pegs_shared" / "phewas.py").read_text(encoding="utf-8")
        regression_source = (REPO_ROOT / "src" / "pegs_shared" / "regression.py").read_text(encoding="utf-8")
        runtime_matrix_source = (REPO_ROOT / "src" / "pegs_shared" / "runtime_matrix.py").read_text(encoding="utf-8")
        bundle_source = (REPO_ROOT / "src" / "pegs_shared" / "bundle.py").read_text(encoding="utf-8")
        pegs_utils_source = (REPO_ROOT / "src" / "pegs_utils.py").read_text(encoding="utf-8")
        self.assertIn("def parse_gene_set_statistics_file(", gene_io_source)
        self.assertIn("def parse_gene_bfs_file(", gene_io_source)
        self.assertIn("def parse_gene_covariates_file(", gene_io_source)
        self.assertIn("def load_aligned_gene_bfs(", gene_io_source)
        self.assertIn("def load_aligned_gene_covariates(", gene_io_source)
        self.assertIn("def coerce_runtime_state_dict(", huge_cache_source)
        self.assertIn("def get_huge_statistics_paths_for_prefix(", huge_cache_source)
        self.assertIn("def build_huge_statistics_meta(", huge_cache_source)
        self.assertIn("def write_huge_statistics_text_tables(", huge_cache_source)
        self.assertIn("def load_huge_statistics_sparse_and_vectors(", huge_cache_source)
        self.assertIn("def resolve_phewas_file_columns(", phewas_source)
        self.assertIn("def prepare_phewas_phenos_from_file(", phewas_source)
        self.assertIn("def read_phewas_file_batch(", phewas_source)
        self.assertIn("def parse_gene_phewas_bfs_file(", phewas_source)
        self.assertIn("def finalize_regression_outputs(", regression_source)
        self.assertIn("def compute_beta_tildes(", regression_source)
        self.assertIn("def compute_logistic_beta_tildes(", regression_source)
        self.assertIn("def correct_beta_tildes(", regression_source)
        self.assertIn("def compute_multivariate_beta_tildes(", regression_source)
        self.assertIn("def compute_banded_y_corr_cholesky(", runtime_matrix_source)
        self.assertIn("def calculate_V_internal(", runtime_matrix_source)
        self.assertIn("def set_runtime_x_from_inputs(", runtime_matrix_source)
        self.assertIn("def set_runtime_sigma(", runtime_matrix_source)
        self.assertIn("def write_bundle_from_specs(", bundle_source)
        self.assertIn("def load_and_apply_bundle_defaults(", bundle_source)
        self.assertIn("from pegs_shared.gene_io import", pegs_utils_source)
        self.assertIn("from pegs_shared.huge_cache import", pegs_utils_source)
        self.assertIn("from pegs_shared.phewas import", pegs_utils_source)
        self.assertIn("from pegs_shared.regression import", pegs_utils_source)
        self.assertIn("from pegs_shared.runtime_matrix import", pegs_utils_source)
        self.assertIn("from pegs_shared.bundle import", pegs_utils_source)
        self.assertNotIn("def parse_gene_set_statistics_file(", pegs_utils_source)
        self.assertNotIn("def parse_gene_bfs_file(", pegs_utils_source)
        self.assertNotIn("def parse_gene_covariates_file(", pegs_utils_source)
        self.assertNotIn("def load_aligned_gene_bfs(", pegs_utils_source)
        self.assertNotIn("def load_aligned_gene_covariates(", pegs_utils_source)
        self.assertNotIn("def coerce_runtime_state_dict(", pegs_utils_source)
        self.assertNotIn("def get_huge_statistics_paths_for_prefix(", pegs_utils_source)
        self.assertNotIn("def build_huge_statistics_meta(", pegs_utils_source)
        self.assertNotIn("def write_huge_statistics_text_tables(", pegs_utils_source)
        self.assertNotIn("def resolve_phewas_file_columns(", pegs_utils_source)
        self.assertNotIn("def prepare_phewas_phenos_from_file(", pegs_utils_source)
        self.assertNotIn("def read_phewas_file_batch(", pegs_utils_source)
        self.assertNotIn("def parse_gene_phewas_bfs_file(", pegs_utils_source)
        self.assertNotIn("def finalize_regression_outputs(", pegs_utils_source)
        self.assertNotIn("def compute_beta_tildes(", pegs_utils_source)
        self.assertNotIn("def compute_logistic_beta_tildes(", pegs_utils_source)
        self.assertNotIn("def correct_beta_tildes(", pegs_utils_source)
        self.assertNotIn("def compute_multivariate_beta_tildes(", pegs_utils_source)
        self.assertNotIn("def compute_banded_y_corr_cholesky(", pegs_utils_source)
        self.assertNotIn("def whiten_matrix_with_banded_cholesky(", pegs_utils_source)
        self.assertNotIn("def calc_X_shift_scale(", pegs_utils_source)
        self.assertNotIn("def calculate_V_internal(", pegs_utils_source)
        self.assertNotIn("def set_runtime_x_from_inputs(", pegs_utils_source)
        self.assertNotIn("def set_runtime_sigma(", pegs_utils_source)
        self.assertNotIn("class BundleManifest", pegs_utils_source)
        self.assertNotIn("class BundleDefaultsApplication", pegs_utils_source)
        self.assertNotIn("def write_bundle_from_specs(", pegs_utils_source)
        self.assertNotIn("def load_and_apply_bundle_defaults(", pegs_utils_source)

    def test_eaggl_legacy_main_uses_package_domain_and_io_layers(self) -> None:
        eaggl_source = (REPO_ROOT / "src" / "eaggl" / "legacy_main.py").read_text(encoding="utf-8")
        self.assertIn("from . import domain as _eaggl_domain", eaggl_source)
        self.assertIn("from . import io as _eaggl_io", eaggl_source)
        self.assertIn("from . import y_inputs as _eaggl_y_inputs", eaggl_source)
        self.assertIn("return _eaggl_dispatch.run_main_pipeline(_build_main_domain(), options)", eaggl_source)

    def test_eaggl_io_uses_pegs_shared_for_extracted_read_helpers(self) -> None:
        io_source = (REPO_ROOT / "src" / "eaggl" / "io.py").read_text(encoding="utf-8")
        self.assertIn("from pegs_shared.io_common import", io_source)
        self.assertIn("from pegs_shared.xdata import", io_source)
        self.assertIn("from . import y_inputs as eaggl_y_inputs", io_source)
        pegs_utils_import_block = io_source.split("from pegs_utils import", 1)[1].split(")\n", 1)[0]
        self.assertNotIn("build_read_x_pipeline_config", pegs_utils_import_block)
        self.assertNotIn("clean_chrom_name", pegs_utils_import_block)
        self.assertNotIn("construct_map_to_ind", pegs_utils_import_block)
        self.assertNotIn("parse_gene_map_file", pegs_utils_import_block)
        self.assertNotIn("read_loc_file_with_gene_map", pegs_utils_import_block)

    def test_eaggl_y_inputs_and_covariates_own_dense_read_y_logic(self) -> None:
        y_source = (REPO_ROOT / "src" / "eaggl" / "y_inputs.py").read_text(encoding="utf-8")
        cov_source = (REPO_ROOT / "src" / "eaggl" / "covariates.py").read_text(encoding="utf-8")
        io_source = (REPO_ROOT / "src" / "eaggl" / "io.py").read_text(encoding="utf-8")
        domain_source = (REPO_ROOT / "src" / "eaggl" / "domain.py").read_text(encoding="utf-8")
        self.assertIn("def read_y_pipeline(", y_source)
        self.assertIn("def _apply_hold_out_chrom(", y_source)
        self.assertIn("def apply_loaded_gene_covariates(", cov_source)
        self.assertIn("return eaggl_y_inputs.read_y_pipeline(", io_source)
        self.assertIn("return eaggl_y_inputs.run_read_y_stage(self, runtime, **read_kwargs)", domain_source)

    def test_eaggl_factor_and_phewas_runtime_methods_live_in_package_modules(self) -> None:
        factor_runtime_source = (REPO_ROOT / "src" / "eaggl" / "factor_runtime.py").read_text(encoding="utf-8")
        phewas_source = (REPO_ROOT / "src" / "eaggl" / "phewas.py").read_text(encoding="utf-8")
        regression_source = (REPO_ROOT / "src" / "eaggl" / "regression.py").read_text(encoding="utf-8")
        flat_source = (REPO_ROOT / "src" / "eaggl" / "legacy_main.py").read_text(encoding="utf-8")
        self.assertIn("def run_factor(", factor_runtime_source)
        self.assertIn("def build_phewas_input_values(", phewas_source)
        self.assertIn("def calculate_phewas_block(", phewas_source)
        self.assertIn("def run_phewas(", phewas_source)
        self.assertIn("def compute_beta_tildes(", regression_source)
        self.assertIn("def compute_multivariate_beta_tildes(", regression_source)
        self.assertIn("def compute_robust_betas(", regression_source)
        self.assertIn("def finalize_regression(", regression_source)
        self.assertIn("from . import factor_runtime as _eaggl_factor_runtime", flat_source)
        self.assertIn("from . import phewas as _eaggl_phewas", flat_source)
        self.assertIn("from . import regression as _eaggl_regression", flat_source)
        self.assertIn("return _eaggl_factor_runtime.run_factor(", flat_source)
        self.assertIn("return _eaggl_phewas.build_phewas_input_values(", flat_source)
        self.assertIn("return _eaggl_phewas.calculate_phewas_block(", flat_source)
        self.assertIn("return _eaggl_phewas.prepare_phewas_phenos_from_file(", flat_source)
        self.assertIn("return _eaggl_phewas.run_phewas(", flat_source)
        self.assertIn("return _eaggl_phewas.run_factor_phewas_batch(", flat_source)
        self.assertIn("return _eaggl_phewas.run_standard_phewas_batch(", flat_source)
        self.assertIn("return _eaggl_regression.compute_beta_tildes(", flat_source)
        self.assertIn("return _eaggl_regression.compute_multivariate_beta_tildes(", flat_source)
        self.assertIn("return _eaggl_regression.compute_robust_betas(", flat_source)
        self.assertIn("return _eaggl_regression.finalize_regression(", flat_source)

    def test_pigean_methods_to_code_doc_points_at_package_modules(self) -> None:
        doc_source = (REPO_ROOT / "docs" / "pigean" / "METHODS_TO_CODE.md").read_text(encoding="utf-8")
        self.assertIn("docs/methods.tex", doc_source)
        self.assertIn("src/pigean/y_inputs.py", doc_source)
        self.assertIn("src/pigean/x_inputs.py", doc_source)
        self.assertIn("src/pigean/pipeline.py", doc_source)
        self.assertIn("src/pigean/gibbs.py", doc_source)
        self.assertIn("src/pigean/huge.py", doc_source)
        self.assertIn("src/pigean/outputs.py", doc_source)

    def test_advanced_set_b_doc_covers_phewas_reuse_decision_modes(self) -> None:
        doc_source = (REPO_ROOT / "docs" / "ADVANCED_SET_B.md").read_text(encoding="utf-8")
        self.assertIn("Decision table:", doc_source)
        self.assertIn("`skip`", doc_source)
        self.assertIn("`re_read_file`", doc_source)
        self.assertIn("`reuse_loaded_matrix`", doc_source)
        self.assertIn("`no_input_requested`", doc_source)
        self.assertIn("`matrix_not_loaded`", doc_source)
        self.assertIn("`loaded_matrix_filtered`", doc_source)
        self.assertIn("`requested_input_matches_loaded_source`", doc_source)
        self.assertIn("tests/test_phewas_stage_reuse_unittest.py", doc_source)
        self.assertIn("tests/test_pegs_utils_bundle_unittest.py", doc_source)

    def test_eaggl_cli_defers_workflow_narrative_to_docs(self) -> None:
        cli_source = (REPO_ROOT / "src" / "eaggl" / "cli.py").read_text(encoding="utf-8")
        workflow_doc = (REPO_ROOT / "docs" / "eaggl" / "WORKFLOWS.md").read_text(encoding="utf-8")
        self.assertIn("docs/eaggl/WORKFLOWS.md", cli_source)
        self.assertNotIn('### F1: Single Phenotype Anchoring', cli_source)
        self.assertNotIn('Options for phenotype-based anchoring of factoring', cli_source)
        self.assertIn("### F1: Single Phenotype Anchoring", workflow_doc)
        self.assertIn("### F9: Gene-set Anchoring", workflow_doc)

    def test_eaggl_labeling_docs_and_cli_make_integrated_command_boundary_explicit(self) -> None:
        cli_source = (REPO_ROOT / "src" / "eaggl" / "cli.py").read_text(encoding="utf-8")
        labeling_doc = (REPO_ROOT / "docs" / "eaggl" / "LABELING.md").read_text(encoding="utf-8")
        workflow_doc = (REPO_ROOT / "docs" / "eaggl" / "WORKFLOWS.md").read_text(encoding="utf-8")
        self.assertIn("there is no separate label mode", cli_source)
        self.assertIn("EAGGL does not expose a separate `label` command.", labeling_doc)
        self.assertIn("Optional labeling stays attached to the same factor command", workflow_doc)

    def test_legacy_core_naming_policy_is_explicit(self) -> None:
        eaggl_legacy = (REPO_ROOT / "src" / "eaggl" / "legacy_main.py").read_text(encoding="utf-8")
        canonical_doc = (REPO_ROOT / "docs" / "CANONICAL_SOURCE.md").read_text(encoding="utf-8")
        readme = (REPO_ROOT / "README.md").read_text(encoding="utf-8")
        self.assertFalse((REPO_ROOT / "src" / "pigean_legacy_main.py").exists())
        self.assertIn("Active transitional EAGGL inner core.", eaggl_legacy)
        self.assertIn("Legacy-core naming policy:", canonical_doc)
        self.assertIn("`src/pigean_legacy_main.py` has been retired", canonical_doc)
        self.assertIn("new logic should go there only when the same change is extracting or shrinking existing ownership", readme)

    def test_package_roots_export_only_bounded_surface(self) -> None:
        pigean_init = (REPO_ROOT / "src" / "pigean" / "__init__.py").read_text(encoding="utf-8")
        eaggl_init = (REPO_ROOT / "src" / "eaggl" / "__init__.py").read_text(encoding="utf-8")
        self.assertIn("_PUBLIC_SUBMODULES = frozenset(", pigean_init)
        self.assertIn("_COMPAT_EXPORTS = {", pigean_init)
        pigean_public_block = pigean_init.split("_PUBLIC_SUBMODULES = frozenset(", 1)[1].split(")\n\n_COMPAT_EXPORTS", 1)[0]
        self.assertNotIn('"legacy_main"', pigean_public_block)
        self.assertNotIn("return getattr(_legacy_module(), name)", pigean_init)
        self.assertNotIn("sorted(set(globals().keys()) | set(dir(_legacy_module())))", pigean_init)
        self.assertIn("_PUBLIC_SUBMODULES = frozenset(", eaggl_init)
        self.assertIn("_COMPAT_EXPORTS = {", eaggl_init)
        eaggl_public_block = eaggl_init.split("_PUBLIC_SUBMODULES = frozenset(", 1)[1].split(")\n\n_COMPAT_EXPORTS", 1)[0]
        self.assertNotIn('"legacy_main"', eaggl_public_block)
        self.assertNotIn("from .legacy_main import *", eaggl_init)

    def test_manifest_normal_visibility_options_have_summaries(self) -> None:
        for rel_path in ("docs/cli_option_manifest.json", "docs/eaggl/cli_option_manifest.json"):
            manifest = json.loads((REPO_ROOT / rel_path).read_text(encoding="utf-8"))
            missing = [
                row["primary_flag"]
                for row in manifest["options"]
                if row.get("public_visibility") == "normal" and not (row.get("summary") or "").strip()
            ]
            self.assertEqual(missing, [], msg="%s missing summaries for: %s" % (rel_path, ", ".join(missing)))

    def test_cli_taxonomy_classifies_core_alias_and_selector_flags(self) -> None:
        src_root = str(REPO_ROOT / "src")
        if src_root not in sys.path:
            sys.path.insert(0, src_root)
        pigean_cli = importlib.import_module("pigean.cli")
        eaggl_cli = importlib.import_module("eaggl.cli")

        pigean_meta = pigean_cli.get_cli_manifest_metadata()
        eaggl_meta = eaggl_cli.get_cli_manifest_metadata()

        self.assertEqual(pigean_meta["--gene-stats-in"]["category"], "method_optional")
        self.assertEqual(pigean_meta["--gene-stats-in"]["public_visibility"], "normal")
        self.assertEqual(pigean_meta["--gene-stats-in"]["documentation_target"], "core_help")
        self.assertEqual(pigean_meta["--num-chains"]["public_visibility"], "normal")
        self.assertEqual(pigean_meta["--params-out"]["category"], "engineering")
        self.assertEqual(pigean_meta["--gene-stats-id-col"]["category"], "engineering")
        self.assertEqual(pigean_meta["--increase-hyper-if-betas-below"]["category"], "compat_alias")
        self.assertEqual(pigean_meta["--gene-phewas-stats-in"]["documentation_target"], "advanced_workflows")

        self.assertEqual(eaggl_meta["--anchor-genes"]["category"], "method_required")
        self.assertEqual(eaggl_meta["--anchor-genes"]["public_visibility"], "normal")
        self.assertEqual(eaggl_meta["--gene-set-stats-id-col"]["category"], "engineering")
        self.assertEqual(eaggl_meta["--gene-phewas-stats-in"]["documentation_target"], "advanced_workflows")
        self.assertEqual(eaggl_meta["--factor-phewas-stats-out"]["category"], "engineering")
        self.assertEqual(eaggl_meta["--factor-phewas-stats-out"]["documentation_target"], "advanced_workflows")

    def test_shared_types_use_concrete_runtime_annotations(self) -> None:
        src_root = str(REPO_ROOT / "src")
        if src_root not in sys.path:
            sys.path.insert(0, src_root)
        pegs_types = importlib.import_module("pegs_shared.types")
        pegs_phewas = importlib.import_module("pegs_shared.phewas")

        x_hints = get_type_hints(pegs_types.XData)
        y_hints = get_type_hints(pegs_types.YData)
        hyper_hints = get_type_hints(pegs_types.HyperparameterData)
        stage_hints = get_type_hints(pegs_types.PhewasStageConfig)

        self.assertNotEqual(x_hints["gene_to_chrom"], Any)
        self.assertNotEqual(x_hints["gene_to_pos"], Any)
        self.assertNotEqual(x_hints["gene_to_huge_score"], Any)
        self.assertNotEqual(y_hints["Y"], Any)
        self.assertNotEqual(y_hints["y_corr_sparse"], Any)
        self.assertNotEqual(hyper_hints["sigma2"], Any)
        self.assertNotEqual(hyper_hints["ps"], Any)
        self.assertNotEqual(stage_hints["gene_phewas_bfs_in"], Any)
        self.assertNotEqual(stage_hints["sparse_frac_betas"], Any)

        self.assertIs(pegs_phewas.PhewasRuntimeState, pegs_types.PhewasRuntimeState)
        self.assertIs(pegs_phewas.FactorInputData, pegs_types.FactorInputData)
        self.assertIs(pegs_phewas.PhewasStageConfig, pegs_types.PhewasStageConfig)
        self.assertIs(pegs_phewas.PhewasInputResolution, pegs_types.PhewasInputResolution)


if __name__ == "__main__":
    unittest.main()
